#!/bin/sh                                                              
#
#                SOLVE_TRF_WEEKLY
#
#             R E M A R K S :                      ecp 960330 Original
#      Add blanks at unit sequence brakes              970729 mod 1
#                                                      000526
#      Modified to handle 7-day L1&2 combined emats    000604
#      Tailored to ITRF solutions                      030219
#
#

set -xv

SCR_NAME=SOLVE_TRF_WEEKLY
SCR_PARM=0
SCR_LIST=""
SCR_VERS=080520.0


if [ `expr $#` -lt $SCR_PARM ]; then
   echo "Usage: $SCR_NAME ${SCR_LIST}\007"
   exit 101
fi

DateTime=`date '+DATE: %m/%d/%y  TIME: %H:%M:%S'`

echo " # "
echo " #  $SCR_NAME $* "
echo " # "
echo " #  Version $SCR_VERS "
echo " # "
echo " #  Run Date $DateTime "
echo " # "


#                SOLVE_TRF_WEEKLY

export NCPUS=1
#
#  CHECK EXISTENCE OF REQUIRED DIRECTORIES :
#
if [ ! -d /${disk}/${slvdir} ]; then
      mkdir /${disk}/${slvdir}     
fi
if [ ! -d /${disk}/${slvdir}/output ]; then
      mkdir /${disk}/${slvdir}/output     
fi
if [ ! -d /${disk}/${slvdir}/output/${PROJ}_out ]; then
      mkdir /${disk}/${slvdir}/output/${PROJ}_out
fi
if [ ! -d /${disk}/${slvdir}/output/${PROJ}_out/$STAGE ]; then
      mkdir /${disk}/${slvdir}/output/${PROJ}_out/$STAGE     
fi
if [ ! -d /${disk}/${slvdir}/output/${PROJ}_out/$STAGE/$SUBCASE ]; then
      mkdir /${disk}/${slvdir}/output/${PROJ}_out/$STAGE/$SUBCASE     
fi
##if [ ! -d /${disk}/${slvdir}/output/${PROJ}_out/$STAGE/$SUBCASE/CASE_$CASE ]; then
##      mkdir /${disk}/${slvdir}/output/${PROJ}_out/$STAGE/$SUBCASE/CASE_$CASE     
##fi
if [ ! -d /${disk}/${slvdir}/unit4 ]; then
      mkdir /${disk}/${slvdir}/unit4     
fi
if [ ! -d /${disk}/${slvdir}/unit5 ]; then
      mkdir /${disk}/${slvdir}/unit5     
fi
if [ ! -d /${disk}/${slvdir}/unit5/$STAGE ]; then
      mkdir /${disk}/${slvdir}/unit5/$STAGE     
fi
if [ ! -d /${disk}/${slvdir}/unit5/$STAGE/$SUBCASE ]; then
      mkdir /${disk}/${slvdir}/unit5/$STAGE/$SUBCASE     
fi
##if [ ! -d /${disk}/${slvdir}/unit5/$STAGE/$SUBCASE/CASE_$CASE ]; then
##      mkdir /${disk}/${slvdir}/unit5/$STAGE/$SUBCASE/CASE_$CASE     
##fi
if [ ! -d /${disk}/${slvdir}/punchdout ]; then
      mkdir /${disk}/${slvdir}/punchdout     
fi
if [ ! -d /${disk}/${slvdir}/punchdout/$STAGE ]; then
      mkdir /${disk}/${slvdir}/punchdout/$STAGE     
fi
if [ ! -d /${disk}/${slvdir}/punchdout/$STAGE/$SUBCASE ]; then
      mkdir /${disk}/${slvdir}/punchdout/$STAGE/$SUBCASE     
fi
##if [ ! -d /${disk}/${slvdir}/punchdout/$STAGE/$SUBCASE/CASE_$CASE ]; then
##      mkdir /${disk}/${slvdir}/punchdout/$STAGE/$SUBCASE/CASE_$CASE     
##fi
if [ ! -d /${disk}/${slvdir}/pgscmt ]; then
      mkdir /${disk}/${slvdir}/pgscmt
fi
if [ ! -d /${disk}/${slvdir}/pgscmt/$STAGE ]; then
      mkdir /${disk}/${slvdir}/pgscmt/$STAGE     
fi
if [ ! -d /${disk}/${slvdir}/pgscmt/$STAGE/$SUBCASE ]; then
      mkdir /${disk}/${slvdir}/pgscmt/$STAGE/$SUBCASE     
fi
##if [ ! -d /${disk}/${slvdir}/pgscmt/$STAGE/$SUBCASE/CASE_$CASE ]; then
##      mkdir /${disk}/${slvdir}/pgscmt/$STAGE/$SUBCASE/CASE_$CASE     
##fi
if [ ! -d /${disk}/${slvdir}/pgscov ]; then
      mkdir /${disk}/${slvdir}/pgscov     
fi
if [ ! -d /${disk}/${slvdir}/pgscov/$STAGE ]; then
      mkdir /${disk}/${slvdir}/pgscov/$STAGE     
fi
if [ ! -d /${disk}/${slvdir}/pgscov/$STAGE/$SUBCASE ]; then
      mkdir /${disk}/${slvdir}/pgscov/$STAGE/$SUBCASE     
fi
##if [ ! -d /${disk}/${slvdir}/pgscov/$STAGE/$SUBCASE/CASE_$CASE ]; then
##      mkdir /${disk}/${slvdir}/pgscov/$STAGE/$SUBCASE/CASE_$CASE     
##fi
if [ ! -d /${disk}/${slvdir}/reference ]; then
      mkdir /${disk}/${slvdir}/reference     
fi
#
#  GO TO A TEMPORARY DIRECTORY :
#

cd /nobackup/mkuzmicz/tmp
mkdir slv$$
cd slv$$

FILENV=.assign
export FILENV

echo $PWD
echo $SOLVE

#
#  LINK TO NEEDED  E-mats & C-mats :
#

##ISUBCASE=B4
#ICASE=24


##cat $MAIN_PATH/INFILES/$LVFLST > filelist

mkdir -p  /$disk/$slvdir/emat/v${SNX_VER}/$STAGE

cat > filelist <<EOF
  1 /$disk/$slvdir/emat/$STAGE/v${SNX_VER}/${ARC}.${CMAT_VERSION}
EOF
 
cat filelist


##cat > filelist <<EOF
##  1 /${disk}/${slvdir}/emat/$STAGE/$ISUBCASE/CASE_$ICASE/z10401p4.e5
##  2 /${disk}/${slvdir}/emat/$STAGE/$ISUBCASE/CASE_$ICASE/z10429p4.e5
##  3 /${disk}/${slvdir}/emat/$STAGE/$ISUBCASE/CASE_$ICASE/z10527p4.e5
##  4 /${disk}/${slvdir}/emat/$STAGE/$ISUBCASE/CASE_$ICASE/z10624p4.e5
##  5 /${disk}/${slvdir}/emat/$STAGE/$ISUBCASE/CASE_$ICASE/z10722p4.e5
##  6 /${disk}/${slvdir}/emat/$STAGE/$ISUBCASE/CASE_$ICASE/z10819p4.e5
##  7 /${disk}/${slvdir}/emat/$STAGE/$ISUBCASE/CASE_$ICASE/z10916p4.e5
##  8 /${disk}/${slvdir}/emat/$STAGE/$ISUBCASE/CASE_$ICASE/z11014p4.e5
##  9 /${disk}/${slvdir}/emat/$STAGE/$ISUBCASE/CASE_$ICASE/z11111p4.e5
## 10 /${disk}/${slvdir}/emat/$STAGE/$ISUBCASE/CASE_$ICASE/z11209p4.e5
## 11 /${disk}/${slvdir}/emat/$STAGE/$ISUBCASE/CASE_$ICASE/z20106p4.e5
## 12 /${disk}/${slvdir}/emat/$STAGE/$ISUBCASE/CASE_$ICASE/z20203p4.e5
## 13 /${disk}/${slvdir}/emat/$STAGE/$ISUBCASE/CASE_$ICASE/z20303p4.e5
## 14 /${disk}/${slvdir}/emat/$STAGE/$ISUBCASE/CASE_$ICASE/z20331p4.e5
## 15 /${disk}/${slvdir}/emat/$STAGE/$ISUBCASE/CASE_$ICASE/z20428p4.e5
## 16 /${disk}/${slvdir}/emat/$STAGE/$ISUBCASE/CASE_$ICASE/z20526p4.e5
##EOF

#
#  JCL :
#
ln -s $SCRIPTS/SOLVE_TRF_WEEKLY              jcl
#cat jcl
#
#  SATELLITE LIST :
#
cat $MAIN_PATH/INFILES/unit1             >                                satids                                                  
#
#  REFERENCE FIELD :
#
#ln -s /${disk}/GISLV/reference/recoef7337b                   reffld
#assign -a reffld                                                    fort.2                                                         
#
#  APRIORI INFO, VALUES - SIGMAS - CONSTRAINTS :
#

ln -s /${disk}/${slvdir}/unit4/$SUBCASE/$LVGRAV                          aprior1

ln -s /${disk}/${slvdir}/unit4/$SUBCASE/$LVTVGC                          aprior2

ln -s /${disk}/${slvdir}/unit4/$SUBCASE/$LVSTAV                          aprior3

ln -s /${disk}/${slvdir}/unit4/$SUBCASE/$LVPOLC                          aprior4

ln -s /${disk}/${slvdir}/unit4/$SUBCASE/$LVPOLR                          aprior41

ln -s /${disk}/${slvdir}/unit4/$SUBCASE/$LVUT1C                          aprior5

ln -s /${disk}/${slvdir}/unit4/$SUBCASE/$LVUT1R                          aprior51

ln -s /${disk}/${slvdir}/unit4/$SUBCASE/$LVBIAS                          aprior6

ln -s /${disk}/${slvdir}/unit4/$SUBCASE/$LVFIXD                          aprior7

ln -s /${disk}/${slvdir}/unit4/$SUBCASE/$LVPARM                          aprior8

ln -s /${disk}/${slvdir}/unit4/$SUBCASE/$LVSATS                          aprior9

ln -s /${disk}/${slvdir}/unit4/$SUBCASE/$LVSATP                          aprior10

#

cat aprior1 aprior2 aprior3 aprior4 aprior41 aprior5 aprior51 aprior6 aprior7 aprior8 aprior9 aprior10    >  aprior  

cp aprior $MAIN_PATH/INFILES/CONSTR_${PROJ}/$STAGE/$SUBCASE/CONSTR.${PROJ}_${SOL}_${WT}

cp aprior /${disk}/${slvdir}/unit4/$SUBCASE/${PROJ}_${SOL}.aprior

#
#  SOLVE CONTROL RECORDS :
#  
ln -s /${disk}/${slvdir}/unit5/$STAGE/$SUBCASE/LVcmat.prt_${SOL}          1unit5
#  
cat 1unit5                      >                                unit5    

#
#  RUN SOLVE  :
#  
#df                                                                              

#time  /u/epavlis/EXECUTABLES/Vsolve_090308.x  <slvin 1>slvft6 2>errout
#time /${diskC}/EXECUTABLES/Vsolve_090308.x   <unit5 >u6.new 2>err.new | asa
time  /nobackup/mkuzmicz/EXECUTABLES/V+solve_G.x   <unit5 >u6.new 2>err.new | asa 




ls -al


#cp fort.7 fort.7.new

#print "\n============================="
#print "\n= error output of NEW_SOLVE ="
#print "\n============================="

cat err.new
 
#echo '======================='
#echo '= output of NEW_SOLVE ='
#echo '======================='

cat u6.new

#print "\n=============================="
#print "\n= fort.3 output of NEW_SOLVE ="
#print "\n=============================="

#cat fort.3
 
#
#  PUT AWAY OUTPUT FILES :  
#  
mv punch  /${disk}/${slvdir}/punchdout/$STAGE/$SUBCASE/v${SNX_VER}/${PROJ}_${SOL}_${WT}pnc
#
mv cmat /${disk}/${slvdir}/pgscmt/$STAGE/$SUBCASE/v${SNX_VER}/${PROJ}_${SOL}_${WT}cmt
#
mv covmat /${disk}/${slvdir}/pgscov/$STAGE/$SUBCASE/v${SNX_VER}/${PROJ}_${SOL}_${WT}cov
#  
#  CLEAN_UP :  
#  
cd ..
\rm -r slv$$                                                                        
                                            
                                            
#  
#  SUBMIT POST_PROCESSING JOBS :  
#
#[ -r /silo/zmjcc/solve/unit7/pgs${SOL} ] && /u2/zmjcc/utility/gcoef.jcl pgs${SOL} short
#[ -r /silo/zmjcc/solve/unit7/pgs${SOL} ] && /u2/zmjcc/utility/sorted.jcl pgs${SOL} short
#[ -r /silo/zmjcc/solve/unit7/pgs${SOL} ] && /u2/zmjcc/utility/recoef.jcl pgs${SOL} short
#[ -r /silo/zmjcc/solve/unit7/pgs${SOL} ] && /u2/zmjcc/utility/tides.ext.jcl pgs${SOL} short

exit
